### ISSUE TITLE
error in ubuntu 16

### ISSUE THREAD

**Issue by markmal** [schwifty42069/piptv#17]
after entering any channel name I got following error:
Traceback (most recent call last):
  File "piptv.py", line 181, in <module>
    main()
  File "piptv.py", line 174, in main
    stb.tune_to_channel(command.split(" --debug")[0])
  File "piptv.py", line 127, in tune_to_channel
    self.player.set_mrl(hotlink)
  File "/usr/local/lib/python3.5/dist-packages/vlc.py", line 3331, in set_mrl
    m = self.get_instance().media_new(mrl, *options)
  File "/usr/local/lib/python3.5/dist-packages/vlc.py", line 1908, in media_new
    if ':' in mrl and mrl.index(':') > 1:
TypeError: argument of type 'NoneType' is not iterable

**Comment by schwifty42069** [comment]
This script has been essentially replaced by its sister script [pmg](https://github.com/schwifty42069/pmg). Pmg has all of the same channels, but it writes them all to an M3U instead, which can be used with VLC or any other compatible media player. The reason piptv doesn't work anymore is because the site it scrapes added anti-bot protection, which I fixed in pmg, but not in piptv yet. I may fix it eventually, but honestly pmg does the same thing, but is more flexible, so I recommend using it rather than waiting for a patch. You can install it using pip like so

```
python3 -m pip install piptv_pmg
```
